Bot-Avançado
BestVelcro/BR-PROGRAMMERS pull request #7
Opened 2017-10-26 22:45 UTC by RodolfoHero

### O que esse pull request adiciona?

  - Irá adicionar um Bot cujo a lib é Discord.js com um "Command Handler" simples.

### Tipo de pull request
  
  - [x] Melhoria do repositório
  - [] Novo projeto

2017-10-26 22:45 UTC, davipatury commented
Mas... Mas... é um novo projeto. :thinking:

2017-10-26 22:46 UTC, Tsugami commented
Pois é

2017-10-27 00:12 UTC, LucasLeandro1204 requested changes

2017-10-27 00:12 UTC, LucasLeandro1204 commented on javascript/discord.js/bot-avançado/comandos/ping.js
> +}
adiciona uma linha branca no final do arquivo

2017-10-27 00:12 UTC, LucasLeandro1204 commented on javascript/discord.js/bot-avançado/index.js
> +    let NomeEvento = file.split(".")[0];
usa const em vez de let no evento e nomeEvento, e usa "nomeEvento"

2017-10-27 00:12 UTC, LucasLeandro1204 commented on javascript/discord.js/bot-avançado/index.js
> +client.on("message", message => {
coloca message entre parenteses

2017-10-27 00:12 UTC, LucasLeandro1204 commented on javascript/discord.js/bot-avançado/index.js
> +client.on("message", message => {
e usa aspas simples no javascript

2017-10-27 00:12 UTC, LucasLeandro1204 commented on javascript/discord.js/bot-avançado/index.js
> +  if (err) return console.error(err);
não faz isso inline, fica feio.
usa sempre 
```
if {

}
```
pra consistência

2017-10-27 00:12 UTC, LucasLeandro1204 commented on javascript/discord.js/bot-avançado/index.js
> +  if (!message.content.startsWith(prefix)) return;
usa assim
```javascript
if (message.author.bot || ! message.content.startsWith(prefix)) {
  return;
}
```

2017-10-27 00:12 UTC, LucasLeandro1204 commented on javascript/discord.js/bot-avançado/index.js
> +  let args = message.content.split(" ").slice(1);
usa const no comando e args

2017-10-27 00:12 UTC, LucasLeandro1204 commented on javascript/discord.js/bot-avançado/index.js
> +    let ArquivoComando = require(`./comandos/${comando}.js`);
const

2017-10-27 00:12 UTC, LucasLeandro1204 commented on javascript/discord.js/bot-avançado/index.js
> +client.login("TOKEN"); // Adcione seu token aqui
aspas simples

2017-10-27 00:25 UTC, Tsugami commented on javascript/discord.js/bot-avançado/index.js
> +  let args = message.content.split(" ").slice(1);
usa assim 
```
const args = msg.content.substring(prefix.length).split(" ");
const comando = args.shift();
```

2017-10-27 00:33 UTC, kaikecarlos reviewed
Esperando a confirmação do velcro

2017-10-27 00:39 UTC, merged